### ISSUE TITLE
Update package.json to reflect Ownership

### ISSUE THREAD

**Issue by ChrisMissal** [HeadspringLabs/gulp-xmlpoke#4]
Since @pedroreys transferred ownership to HSLabs, update the package.json file to reflect this.
- [x] Update file(s)
- [x] Update NPM

**Comment by hulahomer** [comment]
@ChrisMissal what email should we put for the author?

**Comment by ChrisMissal** [comment]
I think it's fine to keep it as @pedroreys as long as he's cool with it. I believe it will have to be his or mine to publish to npm as well. I'm not 100% on that though.

**Comment by pedroreys** [comment]
I don't really care for the email, so I'm cool keeping it or using some other one. Whatever is the easiest to make it work with npm

**Comment by hulahomer** [comment]
@ChrisMissal NPM has now been updated as well.
